name: Create Container

description: >
    Checks if there is a container with the `name`
    and tag equal to a short commit hash of the
    last commit that modified `containerFile`
    input. If there is such an image under
    `username` it will set the output to that
    value otherwise it will rebuild the container
    and push it to the GitHub registry. On `main``
    branch the container will additionally be
    tagged latest and previous latest will be
    deleted.

author: agnesoft

inputs:
    name:
        description: >
            Package name under which the images
            are stored under the username.
            Repository name by default.
        default: ${{ github.repository }}

    username:
        description: >
            Username under which the images
            (packages) are stored.
        default: agnesoft

    containerFile:
        description: >
            File to use for building the image.
            `containerfile` by default.
        default: containerfile

    token:
        description: >
            Personal access token with rights to
            write packages under the user. The
            GITHUB_TOKEN by default.
        default: ${{ github.token }}

outputs:
    image:
        description: >
            Tagged image name that was found or
            created.

    created:
        description: >
            Indicates that the container has been
            created rather than found and reused.

runs:
    using: "node12"
    main: "dist/index.js"
