name: Delete Container

description: >
    Deletes a container tag in GitHub Container
    registry.

author: agnesoft

inputs:
    image:
        description: >
            Tagged container name to be deleted in
            GitHub Container registry format, e.g.
            `ghcr.io/username/image:tag` or
            `username/image:tag`.
        required: true

    token:
        description: >
            Personal access token with permissions
            to `delete packages` for the user
            detected from the `image`. This cannot
            be `GITHUB_TOKEN` because it does not
            have `delete packages` permissions.
        required: true

runs:
    using: "node12"
    main: "dist/index.js"
