name: ADev

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  formatting:
    name: Code Formatting
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Formatting
      run: |
        git fetch origin master
        sudo chmod +x ./build.sh
        if ./build.sh files-to-check; then
          sudo apt-get -qq update
          sudo apt-get -qq install software-properties-common
          sudo add-apt-repository "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-10 main" > /dev/null
          sudo apt-get -qq install clang-format-10
          sudo ln -s /usr/bin/clang-format-10 clang-format
          sudo chmod +x clang-format
          export PATH=.:$PATH
        fi
        ./build.sh check-formatting
        
  coverage:
    name: Code Coverage
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Code Coverage
      run: |
        sudo apt-get -qq update
        sudo apt-get -qq install software-properties-common
        sudo add-apt-repository "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-10 main" > /dev/null
        sudo apt-get -qq install lang-10 clang++-10 llvm-10
        sudo ln -s /usr/bin/clang-10 clang
        sudo ln -s /usr/bin/clang++-10 clang++
        sudo ln -s /usr/bin/llvm-cov-10 llvm-cov
        sudo ln -s /usr/bin/llvm-profdata-10 llvm-profdata
        sudo chmod +x clang
        sudo chmod +x clang++
        sudo chmod +x llvm-cov
        sudo chmod +x llvm-profdata
        curl -L -o ninja.zip https://github.com/ninja-build/ninja/releases/download/v1.10.0/ninja-linux.zip
        unzip ninja.zip
        export PATH=.:$PATH
        sudo chmod +x ./build.sh
        ./build.sh coverage

  build:
    name: ${{ matrix.config.name }}
    needs: [formatting, coverage]
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - { name: "Windows MSVC", os: windows-latest, cc: cl, cxx: cl, ninja: win, platform: windows-msvc2019-x64, }
          - { name: "Linux GCC", os: ubuntu-latest, cc: gcc-9, cxx: g++-9, ninja: linux, platform: linux-gcc9-x64, }
          - { name: "macOS Clang", os: macos-latest, cc: clang, cxx: clang++, ninja: macOS-clang9-x64, }
    steps:
    - uses: actions/checkout@v2
    - name: Build
      shell: bash
      run: |
        curl -L -o ninja.zip https://github.com/ninja-build/ninja/releases/download/v1.10.0/ninja-${{ matrix.config.ninja }}.zip
        unzip ninja.zip
        export PATH=.:$PATH
        chmod +x ./build.sh
        ./build.sh build build ${{ matrix.config.cc }} ${{ matrix.config.cxx }}
    - name: Test
      shell: bash
      run: ./build.sh test build
    - name: Archive
      uses: actions/upload-artifact@v1
      with:
        name: adev-${{ matrix.config.platform }}
        path: build/bin/
