name: ADev

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  check_code:
    name: Check Code
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Formatting
      run: |
        git fetch -q origin master
        COMMITTED_FILES=`git diff --name-only HEAD origin/master | grep 'cpp\|hpp' || [[ $? == 1 ]]`
        if [ ! -z "$COMMITTED_FILES" ]
        then
          sudo apt-get update > /dev/null
          sudo apt-get install software-properties-common > /dev/null
          sudo add-apt-repository "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-10 main" > /dev/null
          sudo apt-get install clang-format-10 > /dev/null
          clang-format-10 -i $COMMITTED_FILES
          UNFORMATTED_FILES=`git ls-files -m | grep 'cpp\|hpp'` || [[ $? == 1 ]]
          if [ ! -z "$UNFORMATTED_FILES" ]
          then
            echo Incorrectly formatted files:
            echo $UNFORMATTED_FILES
            echo Run \'clang-format $UNFORMATTED_FILES\' and commit the result
            exit 1
          fi
        fi

