name: ADev

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  formatting:
    name: Code Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Formatting
        run: ./build.sh check-formatting install

  coverage:
    name: Code Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Code Coverage
        run: ./build.sh coverage install
      - name: Archive
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: adev-code-coverage
          path: build_clang_Coverage/coverage

  analysis:
    name: Static Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Analysis
        run: ./build.sh analyse install

  documentation:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Documentation
        run: ./build.sh documentation install
      - name: Archive
        uses: actions/upload-artifact@v1
        with:
          name: adev-docs
          path: docs/html

  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
              name: "Windows MSVC x64",
              os: windows-latest,
              cc: cl,
              cxx: cl,
              platform: windows-msvc2019-x64,
            }
          - {
              name: "Linux GCC x64",
              os: ubuntu-latest,
              cc: gcc-9,
              cxx: g++-9,
              platform: linux-gcc9-x64,
            }
          - {
              name: "macOS Clang x64",
              os: macos-latest,
              cc: clang,
              cxx: clang++,
              platform: macOS-clang9-x64,
            }
    steps:
      - uses: actions/checkout@v2
      - name: Build
        shell: bash
        run: |
          export CC=${{ matrix.config.cc }}
          export CXX=${{ matrix.config.cxx }}
          export BUILD_DIR=build
          export BUILD_TYPE=Release
          ./build.sh build install
      - name: Test
        shell: bash
        run: |
          export TEST_REPEAT=100
          export BUILD_DIR=build
          ./build.sh test
      - name: Archive
        uses: actions/upload-artifact@v1
        with:
          name: adev-${{ matrix.config.platform }}
          path: build/bin/
