name: adev

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  documentation:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - shell: bash
        run: ./adev.sh install doxygen
      - shell: bash
        run: ./adev.sh build docs

  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./adev.sh format

  linux_clang12_x64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./adev.sh install clang
      - run: ./adev.sh build clang

  linux_gcc11_x64:
    runs-on: ubuntu-latest
    if: false
    steps:
      - uses: actions/checkout@v2
      - run: ./adev.sh install gcc
      - run: ./adev.sh build gcc

  windows_msvc2019_x64:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - shell: bash
        run: ./adev.sh build msvc
