name: ADev

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  check_code:
    name: Check Code
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - name: Formatting
      run: |
        git show-ref
        COMMIT=`git rev-parse HEAD`
        echo $COMMIT
        git show
        if [ ! -z "$COMMITTED_FILES" ]
        then
          echo Installing clang-format-10...
          sudo apt update
          sudo apt install software-properties-common
          sudo add-apt-repository "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-10 main"
          sudo apt install clang-format-10
          echo About to run clang-format-10...
          clang-format-10 -i $COMMITED_FILES
          echo Finished with clang-format-10...
          UNFORMATTED_FILES=`git ls-files -m | grep 'cpp\|hpp'`
          echo UNFORMATTED_FILES are $UNFORMATTED_FILES
          if [ ! -z "$UNFORMATTED_FILES" ]
          then
            echo Incorrectly formatted files:
            echo $UNFORMATTED_FILES
            echo Run \'clang-format $UNFORMATTED_FILES\' and commit the result
            exit 1
          fi
        fi

