name: adev

on:
  push:
    branches: [main]

jobs:
  analysis:
    runs-on: ubuntu-latest
    container: agnesoft/adev
    steps:
      - uses: actions/checkout@v2
      - run: ./adev.sh build clang
      - run: ./adev.sh analyse

  coverage:
    runs-on: ubuntu-latest
    container: agnesoft/adev
    steps:
      - uses: actions/checkout@v2
      - run: ./adev.sh build coverage
      - run: ./adev.sh coverage
      - if: always()
        uses: actions/upload-artifact@v2
        with:
          name: adev-${{ github.run_number }}-coverage
          path: build/coverage/
          if-no-files-found: error

  documentation:
    runs-on: ubuntu-latest
    container: agnesoft/adev
    steps:
      - uses: actions/checkout@v2
      - run: ./adev.sh build docs
      - if: always()
        uses: actions/upload-artifact@v2
        with:
          name: adev-${{ github.run_number }}-documentation
          path: build/docs/
          if-no-files-found: error

  formatting:
    runs-on: ubuntu-latest
    container: agnesoft/adev
    steps:
      - uses: actions/checkout@v2
      - run: ./adev.sh format check

  linux_clang12_x64:
    runs-on: ubuntu-latest
    container: agnesoft/adev
    steps:
      - uses: actions/checkout@v2
      - run: ./adev.sh build clang
      - run: ./adev.sh test clang 100
      - if: always()
        uses: actions/upload-artifact@v2
        with:
          name: adev-${{ github.run_number }}-linux_clang12_x64
          path: build/clang/
          if-no-files-found: error

  linux_gcc11_x64:
    runs-on: ubuntu-latest
    container: agnesoft/adev
    if: false
    steps:
      - uses: actions/checkout@v2
      - run: ./adev.sh build gcc
      - run: ./adev.sh test gcc 100
      - if: always()
        uses: actions/upload-artifact@v2
        with:
          name: adev-${{ github.run_number }}-linux_gcc11_x64
          path: build/gcc/
          if-no-files-found: error

  windows_msvc2019_x64:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - shell: bash
        run: ./adev.sh build msvc
      - shell: bash
        run: ./adev.sh test msvc 100
      - if: always()
        uses: actions/upload-artifact@v2
        with:
          name: adev-${{ github.run_number }}-windows_msvc2019_x64
          path: build/msvc/
          if-no-files-found: error
