name: adev

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  formatting:
    name: formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: format
        shell: bash
        run: ./adev.sh format

  build:
    name: ${{ matrix.config.platform }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
              os: windows-latest,
              platform: windows-msvc2019-x64,
            }
          - {
              os: ubuntu-latest,
              platform: linux-clang12-x64,
            }
    steps:
      - uses: actions/checkout@v2
      - name: build
        shell: bash
        run: ./adev.sh build
