name: adev

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./adev.sh format

  windows_msvc2019_x64:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - shell: bash
        run: ./adev.sh build

  linux_clang12_x64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./adev.sh install clang
      - run: ./adev.sh build
