name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: ${{matrix.config.name}}
    runs-on: ${{matrix.config.runner}}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Ubuntu Latest GCC",
            runner: ubuntu-latest,
            shell: bash,
            environment: "",
            ninja: linux,
            cc: gcc,
            cxx: g++
          }
        - {
            name: "Windows Latest MSVC",
            runner: windows-latest,
            shell: cmd,
            environment: '"C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Auxiliary/Build/vcvars64.bat" && C:/Program Files/Git/bin/bash.exe"',
            ninja: win,
            cc: cl,
            cxx: cl
          }
        - {
            name: "macOS Latest Clang",
            runner: macos-latest,
            shell: bash,
            environment: "",
            ninja: mac,
            cc: clang,
            cxx: clang++
          }
    steps:
    - uses: actions/checkout@v2
    - name: Prepare Environment
      shell: ${{matrix.config.shell}}
      run: |
        ${{matrix.config.environment}}
        mkdir build
        cd build
        curl -L -o ninja.zip https://github.com/ninja-build/ninja/releases/download/v1.10.0/ninja-${{matrix.config.ninja}}.zip
        unzip ninja.zip
      
    - name: Generate Build
      shell: ${{matrix.config.shell}}
      run: |
        ${{matrix.config.environment}}
        export PATH=.:$PATH
        export CC=${{matrix.config.cc}}
        export CXX=${{matrix.config.cxx}}
        cd build
        cmake .. -GNinja -D CMAKE_BUILD_TYPE=Release
        
    - name: Build
      shell: ${{matrix.config.shell}}
      run: |
        ${{matrix.config.environment}}
        cd build
        ninja
