name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    
    - name: Install prerequisites
      run: ./build.sh install-prerequisites

    - name: Build
      run: ./build.sh
