name: macOS Clang

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Prepare
      run: |
        mkdir build
        cd build
        curl -L -o ninja.zip https://github.com/ninja-build/ninja/releases/download/v1.10.0/ninja-mac.zip
        unzip ninja.zip
    - name: Generate
      run: |
        cd build
        export PATH=.:$PATH
        export CC=clang
        export CXX=clang++
        cmake .. -GNinja -D CMAKE_BUILD_TYPE=Release
    - name: Build
      run: |
        cd build
        ./ninja
    - name: Test
      run: |
        cd build
        find . -name "*Test" -type f -exec {} ";"
