name: pr

on:
  pull_request:
    branches: [main]

jobs:
  analysis:
    runs-on: ubuntu-latest
    container: agnesoft/adev
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - id: diff
        run: source sh/common.sh && if is_changed "*.cpp *.hpp **/*.sh"; then (echo "::set-output name=diff::true") fi
      - if: steps.diff.outputs.diff == 'true'
        run: ./adev.sh build clang
      - if: steps.diff.outputs.diff == 'true'
        run: ./adev.sh analyse diff

  coverage:
    runs-on: ubuntu-latest
    container: agnesoft/adev
    if: false
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - id: diff
        run: source sh/common.sh && if is_changed "*.cpp *.hpp **/*.sh"; then (echo "::set-output name=diff::true") fi
      - if: steps.diff.outputs.diff == 'true'
        run: ./adev.sh build coverage
      - if: steps.diff.outputs.diff == 'true'
        run: ./adev.sh coverage
      - if: always() && steps.diff.outputs.diff == 'true'
        uses: actions/upload-artifact@v2
        with:
          name: adev-pr-${{ github.run_number }}-coverage
          path: build/coverage/
          if-no-files-found: error

  documentation:
    runs-on: ubuntu-latest
    container: agnesoft/adev
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - id: diff
        run: source sh/common.sh && if is_changed "*.cpp *.hpp **/*.sh"; then (echo "::set-output name=diff::true") fi
      - if: steps.diff.outputs.diff == 'true'
        run: ./adev.sh build docs
      - if: always() && steps.diff.outputs.diff == 'true'
        uses: actions/upload-artifact@v2
        with:
          name: adev-pr-${{ github.run_number }}-documentation
          path: build/docs/
          if-no-files-found: error

  formatting:
    runs-on: ubuntu-latest
    container: agnesoft/adev
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - id: diff
        run: source sh/common.sh && if is_changed "*.cpp *.hpp **/*.sh"; then (echo "::set-output name=diff::true") fi
      - if: steps.diff.outputs.diff == 'true'
        run: ./adev.sh format check diff

  linux_clang12_x64:
    runs-on: ubuntu-latest
    container: agnesoft/adev
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - id: diff
        run: source sh/common.sh && if is_changed "*.cpp *.hpp **/*.sh"; then (echo "::set-output name=diff::true") fi
      - if: steps.diff.outputs.diff == 'true'
        run: ./adev.sh build clang
      - if: steps.diff.outputs.diff == 'true'
        run: ./adev.sh test clang 100
      - if: always() && steps.diff.outputs.diff == 'true'
        uses: actions/upload-artifact@v2
        with:
          name: adev-pr-${{ github.run_number }}-linux_clang12_x64
          path: build/clang/
          if-no-files-found: error

  linux_gcc11_x64:
    runs-on: ubuntu-latest
    container: agnesoft/adev
    if: false
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - id: diff
        run: source sh/common.sh && if is_changed "*.cpp *.hpp **/*.sh"; then (echo "::set-output name=diff::true") fi
      - if: steps.diff.outputs.diff == 'true'
        run: ./adev.sh install gcc
      - if: steps.diff.outputs.diff == 'true'
        run: ./adev.sh build gcc
      - if: steps.diff.outputs.diff == 'true'
        run: ./adev.sh test gcc 100
      - if: always() && steps.diff.outputs.diff == 'true'
        uses: actions/upload-artifact@v2
        with:
          name: adev-pr-${{ github.run_number }}-linux_gcc11_x64
          path: build/gcc/
          if-no-files-found: error

  windows_msvc2019_x64:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - id: diff
        shell: bash
        run: source sh/common.sh && if is_changed "*.cpp *.hpp **/*.sh"; then (echo "::set-output name=diff::true") fi
      - shell: bash
        if: steps.diff.outputs.diff == 'true'
        run: ./adev.sh build msvc
      - shell: bash
        if: steps.diff.outputs.diff == 'true'
        run: ./adev.sh test msvc 100
      - if: always() && steps.diff.outputs.diff == 'true'
        uses: actions/upload-artifact@v2
        with:
          name: adev-pr-${{ github.run_number }}-windows_msvc2019_x64
          path: build/msvc/
          if-no-files-found: error

