name: Ubuntu GCC

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Prepare
      run: |
        mkdir build
        cd build
        curl -L -o ninja.zip https://github.com/ninja-build/ninja/releases/download/v1.10.0/ninja-linux.zip
        unzip ninja.zip
    - name: Generate
      run: |
        cd build
        export PATH=.:$PATH
        export CC=gcc-9
        export CXX=g++-9
        cmake .. -GNinja -D CMAKE_BUILD_TYPE=Release -D CMAKE_INSTALL_PREFIX=.
    - name: Build
      run: |
        cd build
        ./ninja
    - name: Install
      run: |
        cd build
        ./ninja install
    - name: Archive
      uses: actions/upload-artifact@v1
      with:
        name: adev-linux-gcc-x64
        path: build/bin/

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download
      uses: actions/download-artifact@v1
      with:
        name: adev-linux-gcc-x64
    - name: Test
      run: |
        cd adev-linux-gcc-x64/test
        find -name "*Test" -type f -exec chmod +x {} ";"
        find -name "*Test" -type f -executable -exec {} ";"
