name: Windows MSVC

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Prepare
      shell: bash
      run: |
        mkdir build
        cd build
        curl -L -o ninja.zip https://github.com/ninja-build/ninja/releases/download/v1.10.0/ninja-win.zip
        unzip ninja.zip
    - name: Generate
      shell: cmd
      run: |
        cd build
        set CC=cl
        set CXX=cl
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        cmake .. -GNinja -D CMAKE_BUILD_TYPE=Release -D CMAKE_INSTALL_PREFIX=.
    - name: Build
      shell: cmd
      run: |
        cd build
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        ninja
    - name: Install
      shell: bash
      run: |
        cd build
        ./ninja install
    - name: Archive
      uses: actions/upload-artifact@v1
      with:
        name: adev-windows-msvc-x64
        path: build/bin/

  test:
    needs: build
    runs-on: windows-latest
    steps:
    - name: Download
      uses: actions/download-artifact@v1
      with:
        name: adev-windows-msvc-x64
    - name: Test
      shell: bash
      run: |
        cd adev-windows-msvc-x64/test
        find -name "*Test.exe" -type f -executable -exec {} ";"
